# Generated by Django 4.1 on 2022-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(help_text='Enter 6 digit roll number')),
                ('participation', models.CharField(choices=[('1', 'ኣብ ፍሉይ መደብ ጥራይ ይሳተፍ/ትሳተፍ'), ('2', 'ኣብ ናይ ጽዋአ ኣኼባ ሳሕቲ ይሳተፍ/ትሳተፍ'), ('3', 'ኣብ ኩሉ ዓይነት ኣገልግሎት ኣይሳተፍን/ኣይትሳተፍን')], max_length=200)),
                ('additional_reason', models.TextField()),
                ('member1_name', models.CharField(max_length=200)),
                ('member1_phone', models.IntegerField()),
                ('member2_name', models.CharField(max_length=200)),
                ('member2_phone', models.IntegerField()),
                ('additional_advice', models.TextField()),
            ],
        ),
    ]
