# Generated by Django 4.1 on 2022-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_lostmembermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostmembermodel',
            name='participation',
            field=models.CharField(choices=[('1', 'ኣብ ፍሉይ መደብ ጥራይ ይሳተፍ/ትሳተፍ'), ('2', 'ኣብ ናይ ጽዋአ ኣኼባ ሳሕቲ ይሳተፍ/ትሳተፍ'), ('3', 'ኣብ ኩሉ ዓይነት ኣገልግሎት ኣይሳተፍን/ኣይትሳተፍን')], default=0, max_length=200),
        ),
    ]
