# Generated by Django 4.1 on 2022-09-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_lostmembermodel_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostmembermodel',
            name='participation',
            field=models.CharField(choices=[('1', 'ኣብ ፍሉይ መደብ ጥራይ ይሳተፍ/ትሳተፍ'), ('2', 'ኣብ ናይ ጽዋአ ኣኼባ ሳሕቲ ይሳተፍ/ትሳተፍ'), ('3', 'ኣብ ኩሉ ዓይነት ኣገልግሎት ኣይሳተፍን/ኣይትሳተፍን')], max_length=200),
        ),
        migrations.CreateModel(
            name='MemberFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('current_member', models.IntegerField()),
                ('church_course', models.CharField(max_length=200)),
                ('academic_department', models.CharField(max_length=200)),
                ('additional_course', models.CharField(max_length=200)),
                ('academic_year', models.CharField(choices=[('1', '11'), ('2', '12+1'), ('3', '12+2'), ('4', '12+3'), ('5', '12+4'), ('6', '12+5')], max_length=200)),
                ('other_academic_year', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_number', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
